// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwY_oHEu-iPUJzaoph3sq1pFBtSSUlJlE',
    appId: '1:420467564429:web:fd20bb6e9b665732c6e7c4',
    messagingSenderId: '420467564429',
    projectId: 'flutter-reddit-clone-2298f',
    authDomain: 'flutter-reddit-clone-2298f.firebaseapp.com',
    storageBucket: 'flutter-reddit-clone-2298f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFDIjR49qR2kMEedngguN852_w9snhnWM',
    appId: '1:420467564429:android:fb4b68586ee8f9bec6e7c4',
    messagingSenderId: '420467564429',
    projectId: 'flutter-reddit-clone-2298f',
    storageBucket: 'flutter-reddit-clone-2298f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgmdlgQ4Ka8PwIZw1acMHvLpYitbpNG2I',
    appId: '1:420467564429:ios:32ea5aa31a11b0bac6e7c4',
    messagingSenderId: '420467564429',
    projectId: 'flutter-reddit-clone-2298f',
    storageBucket: 'flutter-reddit-clone-2298f.appspot.com',
    iosClientId: '420467564429-gf04mhmhfaoa7od0544qgbnjkaqn792b.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgmdlgQ4Ka8PwIZw1acMHvLpYitbpNG2I',
    appId: '1:420467564429:ios:32ea5aa31a11b0bac6e7c4',
    messagingSenderId: '420467564429',
    projectId: 'flutter-reddit-clone-2298f',
    storageBucket: 'flutter-reddit-clone-2298f.appspot.com',
    iosClientId: '420467564429-gf04mhmhfaoa7od0544qgbnjkaqn792b.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
